version: "3.9"

services:
  web:
    build: .
    container_name: django_app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      USE_MYSQL: "1"
      MYSQL_DATABASE: django_db
      MYSQL_USER: django_user
      MYSQL_PASSWORD: django_pass
      MYSQL_HOST: db
      CELERY_BROKER_URL: redis://redis:6379/0
    volumes:
      - .:/app
      - media_data:/app/media
    command: >
      sh -c "
      python manage.py wait_for_db &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "

  celery:
    build: .
    container_name: celery_worker
    depends_on:
      - db
      - redis
    environment:
      USE_MYSQL: "1"
      MYSQL_DATABASE: django_db
      MYSQL_USER: django_user
      MYSQL_PASSWORD: django_pass
      MYSQL_HOST: db
      CELERY_BROKER_URL: redis://redis:6379/0
    volumes:
      - .:/app
      - media_data:/app/media
    command: >
      sh -c "
      python manage.py wait_for_db &&
      celery -A core worker -l info
      "

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: django_db
      MYSQL_USER: django_user
      MYSQL_PASSWORD: django_pass
      MYSQL_ROOT_PASSWORD: root_pass
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: redis

volumes:
  mysql_data:
  media_data: