version: "3.9"

services:
  web:
    build: .
    container_name: django_app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      USE_MYSQL: "1"
    volumes:
      - media_data:/app/media
    command: >
      sh -c "
      cd app &&
      python manage.py wait_for_db &&
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn core.wsgi:application --bind 0.0.0.0:8000 --workers 2 --timeout 120
      "

  celery:
    build: .
    container_name: celery_worker
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      USE_MYSQL: "1"
    volumes:
      - media_data:/app/media
    command: >
      sh -c "
      cd app &&
      python manage.py wait_for_db &&
      celery -A core worker -l info --concurrency 2
      "

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: redis

volumes:
  mysql_data:
  media_data: