version: "3.9"

services:
  web:
    image: csv-ingestion-django
    container_name: django_app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      USE_MYSQL: "1"
      MYSQL_DATABASE: django_db
      MYSQL_USER: django_user
      MYSQL_PASSWORD: django_pass
      MYSQL_HOST: db
      CELERY_BROKER_URL: redis://redis:6379/0
    volumes:
      - media_data:/app/media

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: django_db
      MYSQL_USER: django_user
      MYSQL_PASSWORD: django_pass
      MYSQL_ROOT_PASSWORD: root_pass
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: redis

  celery:
    image: csv-ingestion-django
    container_name: celery_worker
    depends_on:
      - redis
      - db
    command: celery -A core worker -l info
    environment:
      USE_MYSQL: "1"
      MYSQL_DATABASE: django_db
      MYSQL_USER: django_user
      MYSQL_PASSWORD: django_pass
      MYSQL_HOST: db
      CELERY_BROKER_URL: redis://redis:6379/0
    volumes:
      - media_data:/app/media

volumes:
  mysql_data:
  media_data:
