# Generated by Django 6.0.1 on 2026-01-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celery_id', models.IntegerField(unique=True)),
                ('status', models.CharField(choices=[('Q', 'Queued'), ('P', 'Running'), ('F', 'Failed'), ('C', 'Completed')], default='Q', max_length=1)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
                ('summary', models.TextField()),
            ],
        ),
    ]
