# Generated by Django 4.2.29 on 2026-03-23 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celery_id', models.CharField(editable=False, max_length=255, unique=True)),
                ('status', models.CharField(choices=[('Q', 'Queued'), ('R', 'Running'), ('F', 'Failed'), ('C', 'Completed')], default='Q', max_length=1)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
            ],
        ),
    ]
