# Generated by Django 6.0.1 on 2026-01-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobstatus',
            name='celery_id',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='jobstatus',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='jobstatus',
            name='status',
            field=models.CharField(choices=[('Q', 'Queued'), ('R', 'Running'), ('F', 'Failed'), ('C', 'Completed')], default='Q', max_length=1),
        ),
    ]
