# Generated by Django 6.0.1 on 2026-01-22 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvapi', '0002_alter_jobstatus_celery_id_alter_jobstatus_started_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobstatus',
            name='celery_id',
            field=models.UUIDField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='jobstatus',
            name='finished_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 22, 17, 22, 6, 394470)),
        ),
    ]
