# Generated by Django 4.2.28 on 2026-06-29 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csvapi', '0002_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobstatus',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jobstatus', to='csvapi.document'),
            preserve_default=False,
        ),
    ]
