# Generated by Django 6.0.1 on 2026-01-23 07:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvapi', '0003_alter_jobstatus_celery_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobstatus',
            name='celery_id',
            field=models.CharField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='jobstatus',
            name='finished_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 23, 12, 30, 14, 305643)),
        ),
    ]
