# Generated by Django 6.0.1 on 2026-01-24 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvapi', '0004_alter_jobstatus_celery_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobstatus',
            name='retry_count',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='jobstatus',
            name='finished_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 24, 13, 4, 17, 719408, tzinfo=datetime.timezone.utc)),
        ),
    ]
